function res = read_pot_proj( fileName )
%READ_POT_PROJ - function for reading potential projections generated by the POTENG program 

global HALO_PATH

fullName=[HALO_PATH '/' fileName]; 

fid=fopen(fullName);

%% read header 
ss=fgetl(fid);

k1=strfind(ss,':');
k2=strfind(ss,',');
bottomLeft=str2num(ss(k1(1)+1:k2(1)));
nGrid=str2num(ss(k1(2)+1:k2(2)));
cellSize=str2num(ss(k1(3)+1:k2(3)));

arr=fscanf(fid,'%f',[prod(nGrid) 1]);

res.bottomLeft=bottomLeft;
res.nGrid=nGrid;
res.cellSize=cellSize;

res.arr=(reshape(arr,nGrid(1),nGrid(2)));


end

