function createfigure_stripped_catalog_with_cumsum(xdata1, ydata1, zdata1, Y1)
%CREATEFIGURE(XDATA1,YDATA1,ZDATA1,Y1)
%  XDATA1:  contour x
%  YDATA1:  contour y
%  ZDATA1:  contour z
%  Y1:  stairs y

%  Auto-generated by MATLAB on 11-Nov-2014 15:56:12

% Create figure
figure1 = figure('PaperSize',[20.98404194812 29.67743169791]);
colormap('hot');

% Create axes
axes1 = axes('Parent',figure1,'Layer','top','FontSize',14);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[6 11]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 100]);
box(axes1,'on');
hold(axes1,'all');

% Create contour
contour(xdata1,ydata1,zdata1,'ShowText','on','LineColor',[0 0 0],...
    'LevelList',[0 10 20 30 40 50 60 70 80 90 100],...
    'Fill','on',...
    'Parent',axes1);

% Create xlabel
xlabel('$ \log(\Sigma_s) \, [\mathrm{M_\odot/kpc^2}]$',...
    'Interpreter','latex',...
    'FontSize',14);

% Create ylabel
ylabel('Stripped Mass $[\%]$','Interpreter','latex','FontSize',14);

% Create colorbar
bar=colorbar('peer',axes1,'FontSize',14);
barTitle(bar,'$\%$ Population')

% Create axes
axes2 = axes('Parent',figure1,'YTick',[0 10 20 30 40 50 60 70 80 90 100],...
    'XTick',[0 10 20 30 40 50 60 70 80 90 100],...
    'Position',[0.544405997693195 0.511796733212341 0.259094579008076 0.368421052631577],...
    'FontSize',12);
box(axes2,'on');
grid(axes2,'on');
hold(axes2,'all');

% Create stairs
stairs(ydata1,Y1,'LineWidth',3,'Parent',axes2);

% Create xlabel
xlabel('Stripped Mass $[\%]$','Interpreter','latex','FontSize',12);

% Create ylabel
ylabel('$\%$ of Population','Interpreter','latex','FontSize',12);

