function cellVal = points2tree(val,treeStruct,method)
%POINTS2TREE - Assign value to each grid cell based on the data points in
%the cell.
%   Given an adaptively sized grid, generated with the tree2d function and
%   stored in the treeStruct data structure, assign a single value for each
%   cell based on the data points in the cell and the method chose (default
%   method: average value. 
%
%  Arguments: 
%       val         - the value of the parameter for each data point.  
%       treeStruct  - data structure generated by tree2d function 
%       method      - which analysis method to be used. Options: average,
%                      median, sum, max, min (default - average value)
% 
%  Output: an array of values for the cells 

% set default method to 'average' 
if ~exist('method','var')
    method='avg';
end

% initialize output 
cellVal=zeros(size(treeStruct.treeLevel));

% run over all cells 
for i=1:length(treeStruct.treeLevel)
    
    % find all points within a given cell 
    maskP=treeStruct.treeBLC(1,i)==treeStruct.pointsBLC(1,:) & ...
        treeStruct.treeBLC(2,i)==treeStruct.pointsBLC(2,:);
    
    
    
    vv=val(maskP);
    mask=~isnan(vv) & ~isinf(vv); % ignore unphysical values .
    
    % assign value based on method 
    switch(lower(method))
        case{'avg','mean'}
            % simple average 
            cellVal(i)=sum(vv(mask))./sum(mask);
            
        case{'sum','total'}
            % sum of all values 
            cellVal(i)=sum(vv(mask));
            
        case{'median','med'}
            % median value
            cellVal(i)=median(vv(mask));
        case{'minimum','min'}
            % minimum  value
            cellVal(i)=min((vv(mask)));
        case{'maximum','max'}
            % maximal value
            cellVal(i)=max(vv(mask));
                        
        otherwise
            error('points2tree - Illegal method: %s',method)
    end
end



end

