global DEFUALT_PRINTOUT_DIR;
printoutdir=sprintf('%s/%s/%s',DEFUALT_PRINTOUT_DIR,'rps_full','alfatest');


mkmap_rps('data',rpscube,'rpscube',rpscube,'rog',rog,'proj',[1 0 0],...
    'vxcube',vx,'vycube',vy,'vzcube',vz,'title','RPS $\alpha=1$','boxx',boxx,'log','on',...
    'contour','rstrip','cont_val',0.1,'alfa',1.0,'rps_v','vvir','msat',1e12,...
    'vfield','yes','dilute',8,'comoving','no',...
    'print','yes','printag','rps_mv10_alf1','printout',printoutdir)

mkmap_rps('data',rpscube,'rpscube',rpscube,'rog',rog,'proj',[1 0 0],...
    'vxcube',vx,'vycube',vy,'vzcube',vz,'title','RPS $\alpha=0.5$','boxx',boxx,'log','on',...
    'contour','rstrip','cont_val',0.1,'alfa',0.5,'rps_v','vvir','msat',1e12,...
    'vfield','yes','dilute',8,'comoving','no',...
    'print','yes','printag','rps_mv10_alf05','printout',printoutdir)

mkmap_rps('data',rpscube,'rpscube',rpscube,'rog',rog,'proj',[1 0 0],...
    'vxcube',vx,'vycube',vy,'vzcube',vz,'title','RPS $\alpha=0.11$','boxx',boxx,'log','on',...
    'contour','rstrip','cont_val',0.1,'alfa',0.1,'rps_v','vvir','msat',1e12,...
    'vfield','yes','dilute',8,'comoving','no',...
    'print','yes','printag','rps_mv10_alf01','printout',printoutdir)

mkmap_rps('data',rpscube,'rpscube',rpscube,'rog',rog,'proj',[1 0 0],...
    'vxcube',vx,'vycube',vy,'vzcube',vz,'title','RPS $f_{gas}=0.05$','boxx',boxx,'log','on',...
    'contour','rstrip','cont_val',0.1,'fgas',0.05,'rps_v','vvir','msat',1e12,...
    'vfield','yes','dilute',8,'comoving','no',...
    'print','yes','printag','rps_mv10_fg005','printout',printoutdir)

mkmap_rps('data',rpscube,'rpscube',rpscube,'rog',rog,'proj',[1 0 0],...
    'vxcube',vx,'vycube',vy,'vzcube',vz,'title','RPS $f_{gas}=0.2$','boxx',boxx,'log','on',...
    'contour','rstrip','cont_val',0.1,'fgas',0.2,'rps_v','vvir','msat',1e12,...
    'vfield','yes','dilute',8,'comoving','no',...
    'print','yes','printag','rps_mv10_fg02','printout',printoutdir)

%% rstrip

mkmap_rps('data',rpscube,'rpscube',rpscube,'rog',rog,'proj',[1 0 0],...
    'vxcube',vx,'vycube',vy,'vzcube',vz,'title','RPS $\alpha=1$','boxx',boxx,'log','on',...
    'contour','mvir','cont_val',1e12,'alfa',1.0,'rps_v','vvir','msat',1e12,...
    'vfield','yes','dilute',8,'comoving','no',...
    'print','yes','printag','rps_rs12_alf1','printout',printoutdir)

mkmap_rps('data',rpscube,'rpscube',rpscube,'rog',rog,'proj',[1 0 0],...
    'vxcube',vx,'vycube',vy,'vzcube',vz,'title','RPS $\alpha=0.5$','boxx',boxx,'log','on',...
    'contour','mvir','cont_val',1e12,'alfa',0.5,'rps_v','vvir','msat',1e12,...
    'vfield','yes','dilute',8,'comoving','no',...
    'print','yes','printag','rps_rs12_alf05','printout',printoutdir)

mkmap_rps('data',rpscube,'rpscube',rpscube,'rog',rog,'proj',[1 0 0],...
    'vxcube',vx,'vycube',vy,'vzcube',vz,'title','RPS $\alpha=0.11$','boxx',boxx,'log','on',...
    'contour','mvir','cont_val',1e12,'alfa',0.1,'rps_v','vvir','msat',1e12,...
    'vfield','yes','dilute',8,'comoving','no',...
    'print','yes','printag','rps_rs12_alf01','printout',printoutdir)

mkmap_rps('data',rpscube,'rpscube',rpscube,'rog',rog,'proj',[1 0 0],...
    'vxcube',vx,'vycube',vy,'vzcube',vz,'title','RPS $f_{gas}=0.05$','boxx',boxx,'log','on',...
    'contour','mvir','cont_val',1e12,'fgas',0.05,'rps_v','vvir','msat',1e12,...
    'vfield','yes','dilute',8,'comoving','no',...
    'print','yes','printag','rps_rs12_fg005','printout',printoutdir)

mkmap_rps('data',rpscube,'rpscube',rpscube,'rog',rog,'proj',[1 0 0],...
    'vxcube',vx,'vycube',vy,'vzcube',vz,'title','RPS $f_{gas}=0.2$','boxx',boxx,'log','on',...
    'contour','mvir','cont_val',1e12,'fgas',0.2,'rps_v','vvir','msat',1e12,...
    'vfield','yes','dilute',8,'comoving','no',...
    'print','yes','printag','rps_rs12_fg02','printout',printoutdir)