%% basic definitions for testing rps maps 
if ~read
    new_env('CL101','csf','a1');
    boxx=8;
    
    
    global DEFAULT_PRINTOUT_DIR;
    printoutdir=sprintf('%s/%s',DEFAULT_PRINTOUT_DIR,'rps_full');
    rog=RHOG(boxx);
    rpscube=rog.*get_vvir().^2;
    
    vx = Vx(boxx);
    vy = Vy(boxx);
    vz = Vz(boxx);
end

if plotmap
%     mkmap_rps('type','rstrip','rpscube',rpscube,'rog',rog,'proj',[1 0 0],...
%         'vxcube',vx,'vycube',vy,'vzcube',vz,'title','RPS $\alpha=1$','titletype','custom',...
%         'boxx',boxx,'log','on',...
%         'limits',[9 12],'strip_model','rstrip','strip_param',0.1,...
%         'contour','alfa','cont_param',1e11,...
%         'alfa',1.0,'rps_v','vvir',...
%         'vfield',[1 0],'dilute',6,'comoving','no')
    
%     mkmap_rps('type','mv_strip_inv','rpscube',rpscube,'rog',rog,'proj',[1 0 0],...
%         'vxcube',vx,'vycube',vy,'vzcube',vz,'title','RPS $\alpha=1$','titletype','custom',...
%         'boxx',boxx,'log','on','rv',[1 1 1],...
%         'limits',[0 0],'strip_model','mv_strip','strip_param',1e11,...
%         'alfa',1.0,'rps_v','vvir',...
%         'vfield',[1 1],'dilute',6,'comoving','no',...
%         'contour','alfa','cont_param',0.05);
    
     mkmap_rps('type','rps_expdisk','rpscube',rpscube,'rog',rog,'proj',[1 0 0],...
        'vxcube',vx,'vycube',vy,'vzcube',vz,'title','RPS exp disk $\Sigma=10^7,\beta=1$','titletype','custom',...
        'boxx',boxx,'log','on','rv',[0 1 0],...
        'limits',[0 0],'strip_model','expdisk_sigma','strip_param',[1e7 1.0 0.1],...
        'alfa',1.0,'rps_v','vvir',...
        'vfield',[1 1],'dilute',6,'comoving','no',....
        'print','yes','printag','rpsdisk_sig7_bet1','printout',printoutdir,'format','both');
    
    mkmap_rps('type','rps_expdisk','rpscube',rpscube,'rog',rog,'proj',[1 0 0],...
        'vxcube',vx,'vycube',vy,'vzcube',vz,'title','RPS exp disk $\Sigma=10^7,\beta=2$','titletype','custom',...
        'boxx',boxx,'log','on','rv',[0 1 0],...
        'limits',[0 0],'strip_model','expdisk_sigma','strip_param',[1e7 2.0 0.1],...
        'alfa',1.0,'rps_v','vvir',...
        'vfield',[1 1],'dilute',6,'comoving','no',....
        'print','yes','printag','rpsdisk_sig7_bet2','printout',printoutdir,'format','both');
    
     mkmap_rps('type','rps_expdisk','rpscube',rpscube,'rog',rog,'proj',[1 0 0],...
        'vxcube',vx,'vycube',vy,'vzcube',vz,'title','RPS exp disk $\Sigma=10^8,\beta=1$','titletype','custom',...
        'boxx',boxx,'log','on','rv',[0 1 0],...
        'limits',[0 0],'strip_model','expdisk_sigma','strip_param',[1e8 1.0 0.1],...
        'alfa',1.0,'rps_v','vvir',...
        'vfield',[1 1],'dilute',6,'comoving','no',....
        'print','yes','printag','rpsdisk_sig8_bet1','printout',printoutdir,'format','both');
    
     mkmap_rps('type','rps_expdisk','rpscube',rpscube,'rog',rog,'proj',[1 0 0],...
        'vxcube',vx,'vycube',vy,'vzcube',vz,'title','RPS exp disk $\Sigma=10^8,\beta=2$','titletype','custom',...
        'boxx',boxx,'log','on','rv',[0 1 0],...
        'limits',[0 0],'strip_model','expdisk_sigma','strip_param',[1e8 2.0 0.1],...
        'alfa',1.0,'rps_v','vvir',...
        'vfield',[1 1],'dilute',6,'comoving','no',....
        'print','yes','printag','rpsdisk_sig8_bet2','printout',printoutdir,'format','both');
end
%mkmap_rps('data',rpscube,'rpscube',rpscube,'proj',[1 1 1],'title','RPS','boxx',boxx,'log','on','contour','rstrip','cont_val',0.1,'rps_v','vvir','vfield','yes','dilute',8)
