batch_process_halo('/home/alf/eladzing/data/kravtsov/clusters/CL24csf1', '%s_a0.999L%dMpc.dat', 'CL24csf1')

batch_process_halo('/home/alf/eladzing/data/kravtsov/clusters/CL6csf1', '%s_a1.001L%dMpc.dat', 'CL6csf1')

batch_process_halo('/home/alf/eladzing/data/kravtsov/clusters/CL10csf1', '%s_a1.000L%dMpc.dat', 'CL10csf1')
batch_process_halo('/home/alf/eladzing/data/kravtsov/clusters/CL11csf1', '%s_a0.999L%dMpc.dat', 'CL11csf1')
batch_process_halo('/home/alf/eladzing/data/kravtsov/clusters/CL14csf1', '%s_a1.001L%dMpc.dat', 'CL14csf1')
batch_process_halo('/home/alf/eladzing/data/kravtsov/clusters/CL5csf1', '%s_a0.999L%dMpc.dat', 'CL5csf1')
batch_process_halo('/home/alf/eladzing/data/kravtsov/clusters/CL7a', '%s_a1.000L%dMpc.dat', 'CL7a')
batch_process_halo('/home/alf/eladzing/data/kravtsov/clusters/CL7csf1', '%s_a1.000L%dMpc.dat', 'CL7csf1')
batch_process_halo('/home/alf/eladzing/data/kravtsov/clusters/CL9csf1', '%s_a0.999L%dMpc.dat', 'CL9csf1')
batch_process_halo('/home/alf/eladzing/data/kravtsov/clusters/LCDM120_CL1_h1', '%s_a0.999L%dMpc.dat', 'LCDM120_CL1_h1')
batch_process_halo('/home/alf/eladzing/data/kravtsov/clusters/LCDM120_CL2_h1', '%s_a1.001L%dMpc.dat', 'LCDM120_CL2_h1')
batch_process_halo('/home/alf/eladzing/data/kravtsov/clusters/LCDM120_CL3_h1', '%s_a1.000L%dMpc.dat', 'LCDM120_CL3_h1')
batch_process_halo('/home/alf/eladzing/data/kravtsov/clusters/LCDM120_CL5_h1', '%s_a1.000L%dMpc.dat', 'LCDM120_CL5_h1')
batch_process_halo('/home/alf/eladzing/data/kravtsov/clusters/LCDM120_CL6_h1', '%s_a1.000L%dMpc.dat', 'LCDM120_CL6_h1')
batch_process_halo('/home/alf/eladzing/data/kravtsov/clusters/LCDM120_CL7_h1', '%s_a1.001L%dMpc.dat', 'LCDM120_CL7_h1')
batch_process_halo('/home/alf/eladzing/data/kravtsov/clusters/LCDM120_CL8_h1', '%s_a0.999L%dMpc.dat', 'LCDM120_CL8_h1')
batch_process_halo('/home/alf/eladzing/data/kravtsov/clusters/LCDM80_CL3_h2', '%s_a1.000L%dMpc.dat', 'LCDM80_CL3_h2')
