%% Import cluster ID's data from text file
% Script for importing data from the following text file:
%
%    filename: /home/zinger/workProjects/matlab_scripts/IllustrisTNG/forGandhali/cluster_galaxy_ids.dat
%
% Auto-generated by MATLAB on 17-Feb-2020 10:25:41

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "VarName1";
opts.VariableTypes = "double";
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl=readtable("/home/zinger/workProjects/matlab_scripts/IllustrisTNG/forGandhali/cluster_galaxy_ids.dat", opts);

%% Convert to output type
clustergalaxyids = tbl.VarName1;

%% Clear temporary variables
clear opts tbl