%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /home/zinger/workProjects/matlab_scripts/IllustrisTNG/forGandhali/control_galaxy_ids.dat
%
% Auto-generated by MATLAB on 17-Feb-2020 10:26:50

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "VarName1";
opts.VariableTypes = "double";
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable("/home/zinger/workProjects/matlab_scripts/IllustrisTNG/forGandhali/control_galaxy_ids.dat", opts);
%% Convert to output type

controlgalaxyids = tbl.VarName1;
%% Clear temporary variables
clear opts tbl