function [fitresult, gof] = fitNFW(rr, mm)
%CREATEFIT(RR,MM)
%  Create a fit.
% ro=mdm./(4*pi/3.*rp.^3)/(deltavir(0)*rho_mean(0));
%  Data for 'untitled fit 1' fit:
%      X Input : rr
%      Y Output: mm
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 12-Oct-2014 11:17:58


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( rr, mm );

% Set up fittype and options.
ft = fittype( 'a*(log(1+c*x)-c*x/(1+c*x))/(log(1+c)-c/(1+c))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf];
opts.StartPoint = [0.546881519204984 0.957506835434298];
opts.Upper = [Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'mm vs. rr', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel( 'rr' );
% ylabel( 'mm' );
% grid on


